debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.web]
    address = ":80"
   [entryPoints.web.http.redirections]
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
network = "traefik"


[certificatesResolvers.lets-encrypt.acme]
  email = "your eamil address"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.httpChallenge]
      entrypoint = "web"
