version: '3.3'
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_acme/acme.json:/acme.json
      - ./traefik_acme/traefik.toml:/traefik.toml
      - ./traefik_acme/traefik_dynamic.toml:/traefik_dynamic.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik
  server:
    image: "pranavgaur/tindog"
    container_name: "tindog"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.rule=Host(`paranjay-test.logicwind.co`)"
     # - "traefik.http.services.server.loadbalancer.server.port=80"
      - "traefik.http.routers.server.tls.certresolver=lets-encrypt"
    networks:
      - traefik
networks:
  traefik:
    external: true
    name: traefik
